version: '3.8'

services:
  stable-diffusion-api:
    build: .
    container_name: stable-diffusion-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_ID=${MODEL_ID:-runwayml/stable-diffusion-v1-5}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s